### ISSUE TITLE
User can search for a card (or cards ) by name

### ISSUE THREAD

**Issue by JCJenvey** [JCJenvey/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a card (or cards ) by name

## 📐 Functionality

The user can type the name of a Magic card into  a search bar and receive details of that card. Partial  names will output a list for the user to choose from.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![search-by-name-wireframe](https://user-images.githubusercontent.com/64106926/231034827-5a737fcc-5a44-4e35-899e-691bca4b0946.png)
![card-list-wireframe](https://user-images.githubusercontent.com/64106926/231034807-e99ae20c-c153-4e60-9ec8-ca9d61826237.png)
![card-info-wireframe](https://user-images.githubusercontent.com/64106926/231034778-a7f5b0eb-d205-4daf-95d4-bb11079a13e3.png)
![mobile-wireframes](https://user-images.githubusercontent.com/64106926/231034882-8eaa4816-056e-4163-a3db-6436b71bc826.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the navbar at the top of the page
- [x] Write CSS for the navbar and the background
- [x] Create a search bar and a button that will eventually be used for generating a random card
- [x] Ensure that the page looks nice with a mobile screen size
- [x] Add an event listener for the "search" event that reads the text in the search bar and uses it to query the API
- [x] Use the data gained from the API to build the card info page
- [x] Make sure the card info page looks good on mobile
- [x] Create a page that lists each card found with the API if there are multiple results. The card names should be buttons
- [x] Add a "click" event listener that shows that details of the card clicked on
- [x] Make sure mobile is fine
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
